# Generated by Django 5.1.7 on 2025-03-20 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=100)),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("gerencia", "Gerencia"),
                            ("ventas", "Ventas"),
                            ("produccion", "Producción"),
                            ("rrhh", "RRHH"),
                            ("compras", "Compras"),
                            ("logistica", "Logística"),
                            ("contabilidad", "Contabilidad"),
                        ],
                        default="ventas",
                        max_length=50,
                    ),
                ),
                ("sueldo_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_contratacion", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sueldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pagado", models.BooleanField(default=False)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="human_resources.empleado",
                    ),
                ),
            ],
        ),
    ]
