# Generated by Django 5.1.7 on 2025-03-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("gerencia", "Gerencia"),
                    ("ventas", "Ventas"),
                    ("produccion", "Producción"),
                    ("rrhh", "RRHH"),
                    ("compras", "Compras"),
                    ("logistica", "Logística"),
                    ("contabilidad", "Contabilidad"),
                ],
                default="ventas",
                max_length=50,
            ),
        ),
    ]
