# Generated by Django 4.2 on 2025-03-19 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelojSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateTimeField(default=django.utils.timezone.now)),
                ('velocidad_simulacion', models.IntegerField(default=3)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reloj de Simulación',
                'verbose_name_plural': 'Reloj de Simulación',
            },
        ),
    ]
