# Generated by Django 5.0.2 on 2025-03-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('publicada', models.BooleanField(default=True)),
                ('coche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizacionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('opcion', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ruedas', 'Ruedas'), ('techo', 'Techo'), ('motor', 'Motor')], default='ruedas', max_length=50)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='ecommerce.coche')),
            ],
        ),
    ]
