# Generated by Django 5.1.6 on 2025-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
