# Generated by Django 5.1.7 on 2025-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_coche'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='coches/'),
        ),
        migrations.AddField(
            model_name='coche',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
