# Generated by Django 5.1.6 on 2025-03-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_coche'),
        ('website', '0002_pagina_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pagina',
            name='coche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche'),
        ),
    ]
