# Generated by Django 5.1.7 on 2025-03-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_coche_imagen_coche_precio_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='coche',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='PersonalizacionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('opcion', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='website.coche')),
            ],
        ),
    ]
