# Generated by Django 5.1.7 on 2025-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_coche_imagen_alter_coche_precio_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacioncomponente',
            name='tipo',
            field=models.CharField(choices=[('ruedas', 'Ruedas'), ('techo', 'Techo'), ('motor', 'Motor')], default='ruedas', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalizacioncomponente',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
