# Generated by Django 5.1.7 on 2025-03-26 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.IntegerField()),
                ('velocidad_maxima', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('color', models.CharField(choices=[('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Blanco', 'Blanco')], default='Negro', max_length=50)),
                ('rueda', models.CharField(choices=[('17"', '17"'), ('19"', '19"'), ('21"', '21"')], default='19"', max_length=10)),
                ('motorizacion', models.CharField(choices=[('V6 3.0L', 'V6 3.0L'), ('V8 4.0L', 'V8 4.0L'), ('Eléctrico 400kW', 'Eléctrico 400kW')], default='V6 3.0L', max_length=50)),
                ('tapiceria', models.CharField(choices=[('Cuero Negro', 'Cuero Negro'), ('Alcantara Roja', 'Alcantara Roja'), ('Tela Gris', 'Tela Gris')], default='Cuero Negro', max_length=50)),
                ('extras', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Techo Panorámico', 'Techo Panorámico'), ('Sistema de Sonido Premium', 'Sistema de Sonido Premium'), ('Asistente de Conducción', 'Asistente de Conducción')], default='Ninguno', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_produccion', 'En Producción'), ('en_almacen', 'En Almacén'), ('en_entrega', 'En Entrega'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rueda_seleccionada', models.CharField(max_length=10)),
                ('motorizacion_seleccionada', models.CharField(max_length=50)),
                ('tapiceria_seleccionada', models.CharField(max_length=50)),
                ('extras_seleccionados', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_ecommerce', to='ecommerce.coche')),
            ],
        ),
    ]
