# Generated by Django 5.1.6 on 2025-03-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.IntegerField()),
                ('velocidad_maxima', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('color', models.CharField(choices=[('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Blanco', 'Blanco')], default='Negro', max_length=50)),
                ('rueda', models.CharField(choices=[('17"', '17"'), ('19"', '19"'), ('21"', '21"')], default='19"', max_length=10)),
                ('motorizacion', models.CharField(choices=[('V6 3.0L', 'V6 3.0L'), ('V8 4.0L', 'V8 4.0L'), ('Eléctrico 400kW', 'Eléctrico 400kW')], default='V6 3.0L', max_length=50)),
                ('tapiceria', models.CharField(choices=[('Cuero Negro', 'Cuero Negro'), ('Alcantara Roja', 'Alcantara Roja'), ('Tela Gris', 'Tela Gris')], default='Cuero Negro', max_length=50)),
                ('extras', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Techo Panorámico', 'Techo Panorámico'), ('Sistema de Sonido Premium', 'Sistema de Sonido Premium'), ('Asistente de Conducción', 'Asistente de Conducción')], default='Ninguno', max_length=200)),
            ],
        ),
    ]
