# Generated by Django 5.1.6 on 2025-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tamanio', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.IntegerField(help_text='Potencia en caballos de fuerza (HP)')),
                ('velocidad_maxima', models.IntegerField(help_text='Velocidad máxima en km/h')),
                ('descripcion', models.TextField()),
                ('color', models.CharField(choices=[('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Azul', 'Azul'), ('Plateado', 'Plateado'), ('Blanco', 'Blanco')], default='Negro', max_length=10)),
                ('rueda', models.CharField(choices=[('17"', '17 pulgadas'), ('19"', '19 pulgadas'), ('21"', '21 pulgadas')], default='19"', max_length=10)),
                ('imagen_3d', models.ImageField(blank=True, null=True, upload_to='coches/')),
            ],
        ),
    ]
