# Generated by Django 5.1.6 on 2025-03-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_coche'),
        ('inventory', '0003_pieza_remove_movimientostock_producto_and_more'),
        ('manufacturing', '0003_remove_ordenproduccion_producto_and_more'),
        ('purchase', '0003_remove_compra_producto_compra_pieza'),
        ('sales', '0004_remove_pedidoitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
