# Generated by Django 5.1.7 on 2025-03-19 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = []
