# Generated by Django 5.1.6 on 2025-03-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('ecommerce', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='crm.cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='coche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ecommerce.coche'),
        ),
    ]
