# Generated by Django 5.1.6 on 2025-03-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pieza_remove_movimientostock_producto_and_more'),
        ('purchase', '0002_compra_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AddField(
            model_name='compra',
            name='pieza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.pieza'),
            preserve_default=False,
        ),
    ]
