# Generated by Django 5.1.7 on 2025-03-19 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("gerente", "Gerente"),
                            ("finanzas", "Finanzas"),
                            ("produccion", "Producción"),
                            ("recursos_humanos", "Recursos Humanos"),
                            ("marketing", "Marketing"),
                            ("cliente", "Cliente"),
                        ],
                        default="administrador",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
