# Generated by Django 5.1.7 on 2025-03-19 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientostock",
            name="costo_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="movimientostock",
            name="numero_referencia",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="movimientostock",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="notas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="stock_maximo",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="stock",
            name="stock_minimo",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="stock",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="movimientostock",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("salida", "Salida"),
                    ("ajuste", "Ajuste"),
                    ("transferencia", "Transferencia"),
                ],
                max_length=20,
            ),
        ),
    ]
