# Generated by Django 5.1.7 on 2025-03-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_movimientostock_costo_unitario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientostock",
            name="precio_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
