# Generated by Django 5.1.6 on 2025-03-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimientostock_fecha_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='producto',
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='pieza',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='inventory.pieza'),
            preserve_default=False,
        ),
    ]
