# Generated by Django 4.2 on 2025-03-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimientostock_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_maximo',
            field=models.IntegerField(default=200),
        ),
    ]
