# Generated by Django 5.1.7 on 2025-03-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('stock_minimo', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_fabricacion_rel', to='ecommerce.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('es_extra', models.BooleanField(default=False)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.componente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.ordenfabricacion')),
            ],
        ),
    ]
