# Generated by Django 4.2 on 2025-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='dummy_field',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
