# Generated by Django 5.1.6 on 2025-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('Planificada', 'Planificada'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], default='Planificada', max_length=20),
        ),
    ]
