# Generated by Django 5.1.7 on 2025-03-19 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenfabricacion",
            name="extras_disponibles",
        ),
        migrations.RemoveField(
            model_name="ordenfabricacion",
            name="motorizacion_disponible",
        ),
        migrations.RemoveField(
            model_name="ordenfabricacion",
            name="ruedas_disponibles",
        ),
        migrations.RemoveField(
            model_name="ordenfabricacion",
            name="tapiceria_disponible",
        ),
        migrations.AddField(
            model_name="componente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ruedas_17", 'Ruedas 17"'),
                    ("ruedas_19", 'Ruedas 19"'),
                    ("ruedas_21", 'Ruedas 21"'),
                    ("motor_v6", "Motor V6 3.0L"),
                    ("motor_v8", "Motor V8 4.0L"),
                    ("motor_electrico", "Motor Eléctrico 400kW"),
                    ("tapiceria_cuero_negro", "Tapicería Cuero Negro"),
                    ("tapiceria_alcantara", "Tapicería Alcantara Roja"),
                    ("tapiceria_tela", "Tapicería Tela Gris"),
                    ("extra_techo", "Techo Panorámico"),
                    ("extra_sonido", "Sistema de Sonido Premium"),
                    ("extra_asistente", "Asistente de Conducción"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordenfabricacion",
            name="extras",
            field=models.ManyToManyField(
                limit_choices_to={"tipo__startswith": "extra_"},
                related_name="ordenes_extras",
                to="manufacturing.componente",
            ),
        ),
        migrations.AddField(
            model_name="ordenfabricacion",
            name="motor",
            field=models.ForeignKey(
                limit_choices_to={"tipo__startswith": "motor_"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_motor",
                to="manufacturing.componente",
            ),
        ),
        migrations.AddField(
            model_name="ordenfabricacion",
            name="ruedas",
            field=models.ForeignKey(
                limit_choices_to={"tipo__startswith": "ruedas_"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_ruedas",
                to="manufacturing.componente",
            ),
        ),
        migrations.AddField(
            model_name="ordenfabricacion",
            name="tapiceria",
            field=models.ForeignKey(
                limit_choices_to={"tipo__startswith": "tapiceria_"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_tapiceria",
                to="manufacturing.componente",
            ),
        ),
    ]
