# Generated by Django 5.1.6 on 2025-03-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_coche'),
        ('manufacturing', '0002_ordenproduccion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='producto',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='coche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche'),
            preserve_default=False,
        ),
    ]
