# Generated by Django 5.1.7 on 2025-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0002_remove_ordenfabricacion_extras_disponibles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ruedas_17", 'Ruedas 17"'),
                    ("ruedas_19", 'Ruedas 19"'),
                    ("ruedas_21", 'Ruedas 21"'),
                    ("motor_v6", "Motor V6 3.0L"),
                    ("motor_v8", "Motor V8 4.0L"),
                    ("motor_electrico", "Motor Eléctrico 400kW"),
                    ("tapiceria_cuero_negro", "Tapicería Cuero Negro"),
                    ("tapiceria_alcantara", "Tapicería Alcantara Roja"),
                    ("tapiceria_tela", "Tapicería Tela Gris"),
                    ("extra_techo", "Techo Panorámico"),
                    ("extra_sonido", "Sistema de Sonido Premium"),
                    ("extra_asistente", "Asistente de Conducción"),
                ],
                default="ruedas_19",
                max_length=50,
            ),
        ),
    ]
