# Generated by Django 4.2 on 2025-03-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_ordenproduccion_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='dummy_field',
        ),
    ]
