# Generated by Django 5.1.7 on 2025-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturing", "0003_alter_componente_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="componente",
            name="stock_actual",
            field=models.IntegerField(default=0),
        ),
    ]
