# Generated by Django 5.1.6 on 2025-03-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cliente_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
    ]
