# Generated by Django 5.1.7 on 2025-03-19 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salarios_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compras_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('salario', 'Salario'), ('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
