# Generated by Django 4.2 on 2025-03-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
