# Generated by Django 5.1.7 on 2025-03-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Blanco', 'Blanco')], default='Negro', max_length=50)),
                ('rueda', models.CharField(choices=[('17"', '17"'), ('19"', '19"'), ('21"', '21"')], default='19"', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.pedido')),
            ],
        ),
    ]
