# Generated by Django 5.1.6 on 2025-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_pedido_estado_pedidoitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
