# Generated by Django 5.1.6 on 2025-03-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_cliente_fecha_registro'),
        ('ecommerce', '0003_coche'),
        ('sales', '0003_alter_pedidoitem_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='coche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='color',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Azul', 'Azul'), ('Plateado', 'Plateado'), ('Blanco', 'Blanco')], default='Negro', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rueda',
            field=models.CharField(choices=[('17"', '17 pulgadas'), ('19"', '19 pulgadas'), ('21"', '21 pulgadas')], default='19"', max_length=10),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='coche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
