# Generated by Django 5.1.7 on 2025-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("objetivo", models.CharField(max_length=200)),
                ("fecha_envio", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("Borrador", "Borrador"), ("Enviada", "Enviada")],
                        default="Borrador",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
