# Generated by Django 5.1.6 on 2025-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Enviada', 'Enviada')], default='Borrador', max_length=20),
        ),
    ]
